### ISSUE TITLE
No SAM header 

### ISSUE THREAD

**Issue by colindaven** [ocxtal/minialign#10]
Hi,

I could run my ONT data through the tool fine.

However the SAM output completely lacks a SAM header. This will make it difficult to do BAM conversion, call SNPs, view in genome browser etc. Is this planned ?

minimap -V
0.2-r123

**Comment by ocxtal** [comment]
Actually the current *minialign* outputs the *general* sam header as follows:

ref: E. coli MG1655
```
@HD     VN:1.0  SO:unsorted
@SQ     SN:gi|556503834|ref|NC_000913.3|        LN:4641652
@PG     ID:minialign    PN:minialign
S1_623  0       gi|556503834|ref|NC_000913.3|   4439847 60      6S29M1I6M1I11M1I12M1I33M1D7M1I13M...
```
ref: human hg38
```
@HD     VN:1.0  SO:unsorted
@SQ     SN:chr1 LN:248956422
@SQ     SN:chr10        LN:133797422
@SQ     SN:chr11        LN:135086622
...
@SQ     SN:chrX LN:156040895
@SQ     SN:chrY LN:57227415
@SQ     SN:chrY_KI270740v1_random       LN:37240
@PG     ID:minialign    PN:minialign
f3920def-68ae-4956-8900-6398064c4f93_Basecall_Alignment_template        4       *       0       0...
```

Please check the version number hitting `minialign -v` and if it says like `0.5.3` or `0.5.2-16-gb6abbc2`, it should supports the three types of the headers, `@HD`, `@SQ`, and `@PG`. If you need another specific header line please inform me of it.

Thanks,

**Comment by colindaven** [comment]
Sorry, my mistake ! Too many minis around.

Analyzed the same sample with minimap/miniasm previously and got mixed up.

Thanks
